name: Deploy to p1 (latest)
run-name: Deploy to p1 
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sap-commerce-ccv2-deployment:
    uses: ./.github/workflows/test.yml
    with:
      branch: "release/*"
      target: p1
      sinceHours: 24
