name: call-deploy-to-s1
run-name: Deploy to s1
on:
  workflow_dispatch:
jobs:
  build-and-deploy-to-s1:
    uses: ./.github/workflows/test.yml
    with:
      branch: "release/*"
      target: s1
      sinceHours: 24
